version: '3'
services:
  caddy:  
    image: joshix/caddy
    links:
      - rstudio
      - netdata 
    volumes:
      - ./site/:/var/www/html
      - ./.caddy/:/.caddy
    ports:
      - 80:80
      - 443:443
    restart: always

  rstudio:
    image: rocker/geospatial 
    env_file: .password 
    volumes:
      - $HOME/students:/home/
    restart: always

  netdata:
    image:titpetric/netdata  
    cap_add:
      - SYS_PTRACE
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - ./netdata.conf:/etc/netdata/netdata.conf
    restart: always


